version: "3.7"
services:
  axon-server:
    image: axoniq/axonserver
    environment:
      - AXONSERVER_EVENTSTORE=/eventstore
      - AXONSERVER_CONTROLDB=/controldb
      - AXONSERVER_HOSTNAME=axon-server
      - AXONSERVER_NAME=axon-server
    volumes:
      - axon-server-eventstore-hotel:/eventstore
      - axon-server-controldb-hotel:/controldb
    ports:
      - "8024:8024"
      - "8124:8124"
    networks:
      - axoniq-hotel
  postgresql:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql-storage-hotel:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - axoniq-hotel
  axoniq-hotel-booking:
    image: axoniq-hotel-booking
    depends_on:
      - postgresql
      - axon-server
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - AXON_AXONSERVER_SERVERS=axon-server
    ports:
      - "8080:8080"
      - "7000:7000"
    networks:
      - axoniq-hotel
volumes:
  axon-server-eventstore-hotel:
  axon-server-controldb-hotel:
  postgresql-storage-hotel:

networks:
  axoniq-hotel:
