apiVersion: v1
kind: Service
metadata:
  name: axonserver
  labels:
    app: axonserver
spec:
  ports:
    - port: 8124
      name: grpc
      targetPort: 8124
  clusterIP: None
  selector:
    app: axonserver
---
apiVersion: v1
kind: Service
metadata:
  name: axonserver-gui
  labels:
    app: axonserver
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8024"
spec:
  type: ClusterIP
  ports:
    - port: 8024
      name: gui
      targetPort: 8024
  sessionAffinity: ClientIP
  selector:
    app: axonserver
