apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-inventory
spec:
  serviceName: "postgres-inventory"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-inventory
  template:
    metadata:
      labels:
        app: postgres-inventory
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: postgres-config-demo-inventory
          ports:
            - containerPort: 5432
              name: postgredb
