apiVersion: v1
kind: Service
metadata:
  name: postgres-inventory
  labels:
    app: postgres-inventory
spec:
  ports:
    - port: 5432
      name: postgres-inventory
  clusterIP: None
  selector:
    app: postgres-inventory
