apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-booking
spec:
  serviceName: "postgres-booking"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-booking
  template:
    metadata:
      labels:
        app: postgres-booking
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: postgres-config-demo-booking
          ports:
            - containerPort: 5432
              name: postgredb
