apiVersion: v1
kind: Service
metadata:
  labels:
    app: axoniq-hotel-booking
  name: axoniq-hotel-booking
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 7000-7000
      port: 7000
      protocol: TCP
      targetPort: 7000
  selector:
    app: axoniq-hotel-booking
  type: LoadBalancer
