apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: axoniq-hotel-booking
  name: axoniq-hotel-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: axoniq-hotel-booking
  template:
    metadata:
      labels:
        app: axoniq-hotel-booking
    spec:
      containers:
        - image: axoniq-hotel-booking:latest
          name: axoniq-hotel-booking
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: axoniq-hotel-booking
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 15
