apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alertmanager/alertmanager-configmap.yml
  - alertmanager/alertmanager-templates-configmap.yml
  - alertmanager/alertmanager-deployment.yml
  - alertmanager/alertmanager-services.yml
  - prometheus/prometheus-configmap.yml
  - prometheus/prometheus-deployment.yml
  - prometheus/prometheus-services.yml
  - grafana/grafana-datasource-configmap.yml
  - grafana/grafana-dashboards-configmap.yml
  - grafana/grafana-deployment.yml
  - grafana/grafana-services.yml
  - opentracing-jaeger/jaeger-deployment.yml
  - opentracing-jaeger/jaeger-services.yml
  - postgres/postgres-booking-configmap.yml
  - postgres/postgres-booking-statefulset.yml
  - postgres/postgres-booking-services.yml
  - axoniq-hotel-booking-deployment.yml
  - axoniq-hotel-booking-services.yml
  - axoniq-hotel-booking-configmap.yml
  - postgres/postgres-inventory-configmap.yml
  - postgres/postgres-inventory-statefulset.yml
  - postgres/postgres-inventory-services.yml
  - axoniq-hotel-inventory-deployment.yml
  - axoniq-hotel-inventory-services.yml
  - axoniq-hotel-inventory-configmap.yml
